# Generated by Django 5.2.1 on 2025-05-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('image', models.CharField(max_length=200)),
                ('airline', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_class', models.CharField(max_length=20)),
                ('seats_available', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_time',
        ),
    ]
